# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 13:19
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0002_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=1000, null=builtins.any),
        ),
    ]
