# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 13:21
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0003_auto_20160921_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=5000, null=builtins.any),
        ),
        migrations.AlterField(
            model_name='news',
            name='publishedDate',
            field=models.CharField(max_length=1000, null=builtins.any),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000, null=builtins.any),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=1000, null=builtins.any),
        ),
        migrations.AlterField(
            model_name='news',
            name='urlToImage',
            field=models.CharField(max_length=1000, null=builtins.any),
        ),
    ]
