# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0007_auto_20160922_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published Date'),
        ),
    ]
