# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0008_auto_20161001_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publishedDate',
            new_name='date',
        ),
    ]
