# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0009_auto_20161001_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='publishedDate',
        ),
    ]
