# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getnews', '0010_auto_20161001_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.FloatField(default=0)),
                ('sports', models.FloatField(default=0)),
                ('business', models.FloatField(default=0)),
                ('entertainment', models.FloatField(default=0)),
                ('science', models.FloatField(default=0)),
                ('technology', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
