# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0011_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='science',
            new_name='science_nature',
        ),
    ]
