# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0012_auto_20161002_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sports',
            new_name='sport',
        ),
    ]
