# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0013_auto_20161006_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='source',
            new_name='sources',
        ),
    ]
