# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getnews', '0014_auto_20161006_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='sources',
            new_name='source',
        ),
    ]
